import type { Character } from './characters.types';
import { generateCharacter } from './characters.utils';

export const ALL_CHARACTERS_DATA: Character[] = [
  generateCharacter({ name: 'Behzat Ç.', image: 'behzat.jpg' }),
  generateCharacter({ name: 'Esra Bulut', image: 'esra.jpg' }),
  generateCharacter({ name: 'Hayalet', image: 'hayalet.jpg' }),
  generateCharacter({ name: 'Akbaba', image: 'akbaba.jpg' }),
  generateCharacter({ name: 'Tahsin Müdür', image: 'tahsin.jpg' }),
  generateCharacter({ name: 'Şevket Ç.', image: 'sevket.jpg' }),
  generateCharacter({ name: 'Şule Şafak', image: 'sule.jpg' }),
  generateCharacter({ name: 'Harun Sinanoğlu', image: 'harun.jpg' }),
  generateCharacter({ name: 'Eda Akkaya', image: 'eda.jpg' }),
  generateCharacter({ name: 'Cevdet', image: 'cevdet.jpg' }),
  generateCharacter({ name: 'Emre', image: 'emra.jpg' }),
  generateCharacter({ name: 'Eylül', image: 'eylul.jpg' }),
  generateCharacter({ name: 'Selim', image: 'selim.jpg' }),
  generateCharacter({ name: 'Aziz', image: 'aziz.jpg' }),
  generateCharacter({ name: 'Suna', image: 'suna.jpg' }),
  // Yardımcı Karakterler
  generateCharacter({ name: 'Ceyda', image: 'ceyda.jpg' }),
  generateCharacter({ name: 'Hüseyin' }),
  generateCharacter({ name: 'Aslı Sinanoğlu', image: 'asli.jpg' }),
  generateCharacter({ name: 'Yalçın Sinanoğlu', image: 'yalcin.jpg' }),
  generateCharacter({ name: 'Elif', image: 'elif.jpg' }),
  generateCharacter({ name: 'Hanımefendi' }),
  generateCharacter({ name: 'Bahri', image: 'bahri.jpg' }),
  generateCharacter({ name: 'Savaş', image: 'savas.jpg' }),
  generateCharacter({ name: 'Psikolog Funda', image: 'funda.jpg' }),
  generateCharacter({ name: 'Sabiha' }),
  generateCharacter({ name: 'Gönül', image: 'gonul.jpg' }),
  generateCharacter({ name: 'Bahar', image: 'bahar.jpg' }),
  generateCharacter({ name: 'Alp', image: 'alp.jpg' }),
  generateCharacter({ name: 'Rahmet Ç.' }),
  generateCharacter({ name: 'Reşat Ç.' }),
  // Konuk Karakterler
  generateCharacter({ name: 'Ercüment Çözer' }),
  generateCharacter({ name: 'Memduh Başgan' }),
  generateCharacter({ name: 'Muzaffer' }),
  generateCharacter({ name: 'Barbaros Tufan' }),
  generateCharacter({ name: 'Gökhan Şenay' }),
  generateCharacter({ name: 'Mine Şafak' }),
  generateCharacter({ name: 'Güngör Şafak' }),
  generateCharacter({ name: 'Cem' }),
  generateCharacter({ name: 'Abi' }),
  generateCharacter({ name: 'Ilgın Çetin' }),
  generateCharacter({ name: 'Feride' }),
  generateCharacter({ name: 'Ayla' }),
  generateCharacter({ name: 'Aslı' }),
  generateCharacter({ name: 'Rüstem' }),
  generateCharacter({ name: 'Yunus' }),
  generateCharacter({ name: 'Berna Ç.' }),
  // Çapraz Karakterler
  generateCharacter({ name: 'Salih' }),
  generateCharacter({ name: 'Gürkan' }),
  generateCharacter({ name: 'Mecnun Çınar' }),
  generateCharacter({ name: 'Erdal Bakkal' }),
  generateCharacter({ name: 'İsmail Abi' }),
  generateCharacter({ name: 'İskender Çınar' }),
  generateCharacter({ name: 'Hırsız Yavuz' }),
  generateCharacter({ name: 'Ak Sakallı Dede' }),
  generateCharacter({ name: 'Yedek Kamil' }),
  generateCharacter({ name: 'Ahmet Doğru' }),
  // Film Karakterleri
  generateCharacter({ name: 'Cafer' }),
  generateCharacter({ name: 'Melisa' }),
  generateCharacter({ name: 'Ulrike' }),
  generateCharacter({ name: 'Hans' }),
  generateCharacter({ name: 'Emin Altınkaya (Red Kit)' }),
  generateCharacter({ name: 'Songül' }),
  generateCharacter({ name: 'Cengiz İpek (Pembo)' }),
  generateCharacter({ name: 'Hasan (Gorbaçov)' }),
  generateCharacter({ name: 'Ahmet Kolsuz (Süleyman)' }),
  generateCharacter({ name: 'Avukat' }),
];
